<?php

namespace App\Support;

use Illuminate\Support\Facades\Storage;

/**
 * Builds a srcset for images that live on the public storage disk.
 *
 * Variants are generated by `php artisan images:variants` as
 * {basename}-{width}w.{ext} files next to the original. If no variants
 * exist yet, srcset() returns null and the <img> keeps its plain src —
 * so views can be deployed before the command has run on the server.
 */
class ResponsiveImage
{
    public const WIDTHS = [480, 800, 1200, 1600];

    public static function srcset(?string $url): ?string
    {
        if (!$url) {
            return null;
        }

        $path = parse_url($url, PHP_URL_PATH);
        if (!$path || !str_contains($path, '/storage/')) {
            return null;
        }

        $rel = ltrim(substr($path, strpos($path, '/storage/') + strlen('/storage/')), '/');
        $ext = pathinfo($rel, PATHINFO_EXTENSION);
        if ($ext === '') {
            return null;
        }

        $base = substr($rel, 0, -(strlen($ext) + 1));
        $disk = Storage::disk('public');

        $sources = [];
        foreach (self::WIDTHS as $width) {
            $variant = "{$base}-{$width}w.{$ext}";
            if ($disk->exists($variant)) {
                $sources[] = asset("storage/{$variant}") . " {$width}w";
            }
        }

        return $sources === [] ? null : implode(', ', $sources);
    }
}
